PHP = hhvm
COMPOSER = $(PHP) composer.phar
PHPUNIT = vendor/bin/phpunit
CONSOLE = $(PHP) artisan

test:
	$(PHP) $(PHPUNIT)

install: update cache compile test up

compile:
	$(CONSOLE) ui:compile
	lessc --clean-css resources/assets/less/app.less public/css/style.css

sync:
	git pull

down:
	$(CONSOLE) down

up: cache
	$(CONSOLE) up

update: down clear sync
	$(COMPOSER) self-update
	$(COMPOSER) update --no-dev -o --profile -vv

clear:
	$(CONSOLE) clear-compiled
	$(CONSOLE) view:clear
	$(CONSOLE) cache:clear
	$(CONSOLE) config:clear
	$(CONSOLE) session:clear

cache:
	$(CONSOLE) optimize
	$(CONSOLE) config:cache
